### ISSUE TITLE
`sinon.assert` not available?

### ISSUE THREAD

**Issue by ljharb** [wealthfront/sinon-sandbox#7]
In our codebase, we use `import sinon from 'sinon-sandbox'`, and have a linter rule that forbids importing `sinon` directly. However, this means we can't use `sinon.assert`.

Would you be willing to accept a PR that attaches `sinon.assert` to the exported sandbox?

**Comment by TheSavior** [comment]
Hmm. I took a look at how we do this in our codebase and we use 
```
const sinon = require('sinon') // linter ignore this line
sinon.assert.expose(chai.assert, {
  prefix: ''
});
```

It is nice the way this module is right now in that it is a complete passthrough to sinon's own sandbox instance. I'm slightly concerned to change that due to there being many other things to expose as well if we go down that path. I wonder if there is any negative effect to exporting things on the sandbox function.

It is interesting that [sinon exposes `.match` on the sandbox object](https://github.com/sinonjs/sinon/blob/master/lib/sinon/sandbox.js#L135). I wonder if they'd be willing to expose assert there so we can pull it in downstream. 

While we are discussing this, are you able to do something functionally similar like this to get the effect you are hoping to get, for now?

```
const sinon = require('sinon') // linter ignore this line
const sinonSandbox = require('sinon-sandbox');
sinonSandbox.assert = {};
sinon.assert.expose(sinonSandbox.assert, {
  prefix: ''
});
```

**Comment by ljharb** [comment]
Having `sinon` itself expose it seems much better, that is true.

I certainly could do that - but mutation is bad news bears and I'd prefer to not do that :-)

Filed https://github.com/sinonjs/sinon/issues/1075 as well. I think it's best if sinon itself does this, but I also think it would be a good addition to sinon-sandbox in the meantime.

**Comment by ljharb** [comment]
Posted https://github.com/sinonjs/sinon/pull/1076 - hopefully that will be accepted.

**Comment by ljharb** [comment]
Hooray! It's merged. Now I just need to wait for the release :-)

**Comment by TheSavior** [comment]
Great news!
